# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/ruby:2.5.1-node-browsers
        environment:
          - DATABASE_HOST=127.0.0.1
          - DATABASE_USER=root
          - DATABASE_PASSWORD=circleci
          - RAILS_ENV=test
      - image: circleci/mysql:5.7
        environment:
          - MYSQL_ROOT_PASSWORD=circleci

    working_directory: ~/member_management

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "Gemfile.lock" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle

      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}

      # Database setup
      - run: mv ./config/database.yml.sample ./config/database.yml
      - run: bundle exec rake db:create
      - run: bundle exec rake db:migrate

      # run rubocop
      - run:
          name: run rubocop
          command: bundle exec rubocop

      # run tests!
      - run:
          name: run tests
          command: |
            mkdir /tmp/test-results
            bundle exec rspec --format progress \
                            --out /tmp/test-results/rspec.xml
          # command: |
          # bundle exec rspec --format progress \
          #                 --format RspecJunitFormatter \
          #                 --out /tmp/test-results/rspec.xml \
          #                 --format progress

      # collect reports
      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results
          destination: test-results
